<?php

namespace App\Services;

use App\Models\PriceRequest;

class PriceRequestPdfService
{
    private const PAGE_WIDTH = 595.0;
    private const PAGE_HEIGHT = 842.0;
    private const MARGIN = 36.0;

    public function generate(PriceRequest $priceRequest): string
    {
        $ops = [];
        $y = self::PAGE_HEIGHT - self::MARGIN;

        $this->drawBackground($ops);
        $this->drawHeader($ops, $priceRequest, $y);
        $y -= 84;

        $y = $this->drawTwoColumnInfo($ops, $y, [
            ['Company Name', $priceRequest->company_name ?: '-'],
            ['Contact Person', $priceRequest->contact_person ?: '-'],
            ['Email', $priceRequest->email ?: '-'],
            ['Phone', $priceRequest->phone ?: '-'],
            ['Company Type', $priceRequest->company_type_label ?: '-'],
            ['Employee Count', (string) ($priceRequest->employee_count ?: '-')],
            ['Budget Range', $priceRequest->budget_range_label ?: '-'],
            ['Timeline', $priceRequest->timeline_label ?: '-'],
        ]);

        $y -= 16;

        $y = $this->drawSection($ops, $y, 'Services Needed', $priceRequest->services_needed ?: '-');
        $y = $this->drawSection($ops, $y - 10, 'Additional Requirements', $priceRequest->additional_requirements ?: '-');
        $y = $this->drawSection($ops, $y - 10, 'Response Notes', $priceRequest->response_notes ?: '-');

        $this->drawFooter($ops);

        $stream = implode("\n", $ops);

        return $this->buildPdf($stream);
    }

    private function drawBackground(array &$ops): void
    {
        // Light page background.
        $ops[] = '0.98 0.99 1 rg';
        $ops[] = '0 0 595 842 re f';
    }

    private function drawHeader(array &$ops, PriceRequest $request, float $topY): void
    {
        $x = self::MARGIN;
        $w = self::PAGE_WIDTH - (self::MARGIN * 2);
        $h = 64;
        $bottom = $topY - $h;

        // Header card.
        $ops[] = '0.14 0.20 0.31 rg';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re f', $x, $bottom, $w, $h);

        $this->text($ops, $x + 14, $topY - 24, 16, 'Helvetica-Bold', 'Price Request', [1, 1, 1]);
        $this->text($ops, $x + 14, $topY - 44, 10, 'Helvetica', 'Request #' . $request->id, [0.92, 0.95, 1]);

        $meta = 'Created: ' . ($request->created_at?->format('Y-m-d H:i') ?? '-') . '   |   Status: ' . ($request->status ? 'Responded' : 'Pending');
        $this->text($ops, $x + 220, $topY - 44, 9, 'Helvetica', $meta, [0.92, 0.95, 1]);
    }

    private function drawTwoColumnInfo(array &$ops, float $startY, array $rows): float
    {
        $x = self::MARGIN;
        $totalW = self::PAGE_WIDTH - (self::MARGIN * 2);
        $gap = 12;
        $colW = ($totalW - $gap) / 2;
        $rowH = 36;
        $y = $startY;

        for ($i = 0; $i < count($rows); $i += 2) {
            $left = $rows[$i];
            $right = $rows[$i + 1] ?? ['', ''];
            $bottom = $y - $rowH;

            $this->fieldCard($ops, $x, $bottom, $colW, $rowH, $left[0], $left[1]);
            $this->fieldCard($ops, $x + $colW + $gap, $bottom, $colW, $rowH, $right[0], $right[1]);

            $y -= ($rowH + 8);
        }

        return $y;
    }

    private function drawSection(array &$ops, float $topY, string $title, string $value): float
    {
        $x = self::MARGIN;
        $w = self::PAGE_WIDTH - (self::MARGIN * 2);
        $textLines = $this->wrap($value, 105);
        $contentH = max(52, count($textLines) * 12 + 26);
        $bottom = $topY - $contentH;

        // Card.
        $ops[] = '1 1 1 rg';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re f', $x, $bottom, $w, $contentH);
        $ops[] = '0.87 0.90 0.95 RG';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re S', $x, $bottom, $w, $contentH);

        $this->text($ops, $x + 10, $topY - 16, 10, 'Helvetica-Bold', $title);

        $ty = $topY - 32;
        foreach ($textLines as $line) {
            $this->text($ops, $x + 10, $ty, 9.5, 'Helvetica', $line);
            $ty -= 12;
        }

        return $bottom;
    }

    private function drawFooter(array &$ops): void
    {
        $this->text($ops, self::MARGIN, 20, 8.5, 'Helvetica', 'Generated by Listing Dashboard');
    }

    private function fieldCard(array &$ops, float $x, float $y, float $w, float $h, string $label, string $value): void
    {
        $ops[] = '1 1 1 rg';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re f', $x, $y, $w, $h);
        $ops[] = '0.87 0.90 0.95 RG';
        $ops[] = sprintf('%.2F %.2F %.2F %.2F re S', $x, $y, $w, $h);

        $this->text($ops, $x + 10, $y + $h - 13, 8.5, 'Helvetica-Bold', $label);
        $this->text($ops, $x + 10, $y + 11, 10, 'Helvetica', $this->truncate($value, 42));
    }

    private function text(array &$ops, float $x, float $y, float $size, string $font, string $text, array $rgb = [0.13, 0.16, 0.22]): void
    {
        $fontName = $font === 'Helvetica-Bold' ? '/F2' : '/F1';
        $safeText = $this->sanitize($text);
        $ops[] = sprintf('%.2F %.2F %.2F rg', $rgb[0], $rgb[1], $rgb[2]);
        $ops[] = "BT {$fontName} {$size} Tf {$x} {$y} Td ({$safeText}) Tj ET";
    }

    private function wrap(string $text, int $maxChars): array
    {
        $text = trim(preg_replace('/\s+/', ' ', $text) ?? '');
        if ($text === '') {
            return ['-'];
        }

        $chunks = [];
        while (strlen($text) > $maxChars) {
            $slice = substr($text, 0, $maxChars);
            $lastSpace = strrpos($slice, ' ');
            if ($lastSpace !== false) {
                $slice = substr($slice, 0, $lastSpace);
            }
            $chunks[] = trim($slice);
            $text = trim(substr($text, strlen($slice)));
        }
        $chunks[] = $text;

        return array_map(fn ($line) => $this->sanitize($line), $chunks);
    }

    private function truncate(string $text, int $max): string
    {
        $text = trim($text);
        if (strlen($text) <= $max) {
            return $this->sanitize($text);
        }

        return $this->sanitize(substr($text, 0, $max - 3) . '...');
    }

    private function sanitize(string $text): string
    {
        $text = preg_replace('/[^\x20-\x7E]/', '?', $text) ?? '';
        return str_replace(['\\', '(', ')'], ['\\\\', '\(', '\)'], $text);
    }

    private function buildPdf(string $stream): string
    {
        $objects = [];
        $objects[] = '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj';
        $objects[] = '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj';
        $objects[] = '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 6 0 R >> >> /Contents 5 0 R >> endobj';
        $objects[] = '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj';
        $objects[] = '5 0 obj << /Length ' . strlen($stream) . " >> stream\n" . $stream . "\nendstream endobj";
        $objects[] = '6 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj';

        $pdf = "%PDF-1.4\n";
        $offsets = [0];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object . "\n";
        }

        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 " . (count($objects) + 1) . "\n";
        $pdf .= "0000000000 65535 f \n";

        for ($i = 1; $i <= count($objects); $i++) {
            $pdf .= sprintf('%010d 00000 n ', $offsets[$i]) . "\n";
        }

        $pdf .= "trailer << /Size " . (count($objects) + 1) . " /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }
}
